<template>
	<svg class="inj-map-feature-patterns" xmlns="http://www.w3.org/2000/svg">
	<!-- These defs can't be in the map SVG because that one is being auto-generated by leaflet. It would be possible to inject them into the DOM right there after the fact, but this is easire and more readable, I think. -->
		<defs>
			<pattern
				class="inj-map-feature__swamp--pattern"
				id="swampPattern"
				x="0"
				y="0"
				width="4"
				height="4"
				patternUnits="userSpaceOnUse"
			>
				<circle cx="2" cy="2" r="1"></circle>
			</pattern>
			<pattern
				class="inj-map-feature__mountain-range--pattern"
				id="mountainPattern"
				viewBox="0,0,30,30"
				width="8"
				height="8"
				patternUnits="userSpaceOnUse"
			>
				<path d="M8 2.156l-1.406 1.438-6.594 6.563v5.688l.125-.125 7.875-7.906 8 8v-5.625l-6.594-6.594-1.406-1.438z"></path>
			</pattern>
		</defs>
	</svg>	
</template>

export default {
	name: 'mapFeaturePatterns'
}
